modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
modId="funnier_death"
version="${file.jarVersion}"
displayName="Funnier Death"
logoFile="laughing_skull_so_funny.png"
credits="My dumb brain and Frenderman (magnificent logo)"
authors="Sarinsa"
description='''

    A very mod that really does.

'''
[[dependencies.funnier_death]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.funnier_death]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
